# Generated by Django 6.0.3 on 2026-04-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq_cz', '0002_faq_category_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='faq',
            new_name='faq_cz_faq_is_acti_261518_idx',
            old_name='faq_cz_faq_is_acti_3df0e8_idx',
        ),
        migrations.RenameIndex(
            model_name='faq',
            new_name='faq_cz_faq_categor_a1bb70_idx',
            old_name='faq_cz_faq_categor_2b08ea_idx',
        ),
    ]
