# Generated by Django 5.2.6 on 2026-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_user', '0002_customuser_birth_date_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='users/user_img/cat_dp.png', null=True, upload_to='users/user_img/'),
        ),
    ]
