# Generated by Django 6.0.3 on 2026-04-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_cz', '0003_reportimage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='report_cz_c_created_eb2dc9_idx',
            old_name='report_cz_c_created_6f2f6f_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='report_cz_c_parent__3d5854_idx',
            old_name='report_cz_c_parent__b59e38_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='report_cz_r_status_392e2a_idx',
            old_name='report_cz_r_status_71474d_idx',
        ),
    ]
