# Generated by Django 5.2.6 on 2026-04-11 11:23

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_cz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='message_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group', 'created'], name='community_c_group_i_c68573_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['author', 'created'], name='community_c_author__d0b417_idx'),
        ),
    ]
